name: 构建文档
on: 
  push:
    branches:
      - docs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Night-stars-1/Honkai-Star-Rail-Docs
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist
<<<<<<< HEAD
        CNAME: sra.stysqy.top
=======
        CNAME: sra.stysqy.top
>>>>>>> f5d833c212bfdae9cadcbf70df31912b441e796b
